// SEARCH
export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';

// ADD TRACK
export const ADD_TRACK = 'ADD_TRACK';

// DELETE TRACK
export const DELETE_TRACK = 'DELETE_TRACK';

// EDIT TRACK
export const EDIT_TRACK = 'EDIT_TRACK';
